project_identifier: neptune-web-components
project_id: CROWDIN_PROJECT_ID
api_token: CROWDIN_ENTERPRISE_TOKEN
preserve_hierarchy: true
files:
  - source: /packages/components/src/i18n/en.json
    translation: /packages/components/src/i18n/%two_letters_code%.%file_extension%
    languages_mapping:
      two_letters_code:
        zh-HK: zh
    update_option: update_as_unapproved
  - source: /packages/dynamic-flows/src/i18n/en.json
    translation: /packages/dynamic-flows/src/i18n/%two_letters_code%.%file_extension%
    languages_mapping:
      two_letters_code:
        zh-HK: zh
    update_option: update_as_unapproved
