name: Crowdin download

on:
  schedule:
    - cron: '0 7 * * 1-5'

jobs:
  download-from-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get branch name
        id: vars
        run: echo ::set-output name=branch_name::${GITHUB_REF##*/}

      - name: crowdin action
        uses: crowdin/github-action@1.3.1
        with:
          upload_translations: false
          download_translations: true
          localization_branch_name: l10n_${{ steps.vars.outputs.branch_name }}
          create_pull_request: true
          pull_request_title: 'New or updated Crowdin translations'
          pull_request_body: '## Context

            Automated pull request pulling in new or updated translations from Crowdin'

          pull_request_labels: 'change:standard'
          pull_request_base_branch_name: ${{ steps.vars.outputs.branch_name }}

          # signing commits
          gpg_private_key: ${{ secrets.GPG_SIGN_KEY }}
          github_user_email: 'tw-actions@transferwise.com'

          # integration settings
          base_url: 'https://transferwise.crowdin.com'
          crowdin_branch_name: ${{ steps.vars.outputs.branch_name }}
          token: ${{ secrets.CROWDIN_ENTERPRISE_TOKEN }}
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }} # Add as repository secret — number from transferwise.crowdin.com project URL

        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
