name: Crowdin upload

on:
  push:
    branches:
      - main

jobs:
  upload-to-crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: crowdin action
        uses: crowdin/github-action@1.3.1
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false
          base_url: 'https://transferwise.crowdin.com'
          token: ${{ secrets.CROWDIN_ENTERPRISE_TOKEN }}
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
